language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_e469301da145_key -iv $encrypted_e469301da145_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- export TZ='Asia/Shanghai'
install:
- npm install gitbook-cli -g
- gitbook install
script:
- gitbook build .
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  local-dir: _book
  on:
    branch: master
